

name: Teste-cypress

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - name: Instalar Dependencias 
      run: npm install

    - name: Executar testes
      run: npm test
    - name: Gerar relatorio Allure
      run: npm run report:generate

    - name: Publicar relatorio no Gh Pages 
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public